### ISSUE TITLE
Write a shell script that installs and start iot edge with user supplied connection string

### ISSUE THREAD

**Issue by heobim10** [social-experiments/EduOnEdge#32]
**//5/8 ::
try the new shared script / connection string and see if it works 
Share your script with tiona to integrate with the app 
    - configure 
    - delete** 
             

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux

now that you have the instruction log into the ubuntu VM/device to test 
ssh mahesh@impacttest.westus2.cloudapp.azure.com
pswd:: Microsoft123

Connection string for your testing 

HostName=yadavm.azure-devices.net;DeviceId=testimpact;SharedAccessKey=SEAikj/j+mcNo73b+/9W7/4Z41Cw+fCr6/d5aC7btMk=

**Comment by initmahesh** [comment]
her is ascript that does half of waht you are trying to do 
https://github.com/psakamoori/intel-rrk-custom-vision/blob/master/OOBE/az-iot-edge-runtime-install.sh

NOTE:: this one doe snto udpate the connection string in /etc/iotedge/congi.yaml

for that you can use sed -i 
i tested as below and it worked for me for a quick test
     sudo cp /etc/iotedge/config.yaml /etc/iotedge/config.yaml_backup
      sudo sed -i "/device_connection_string:/c\mchanges" /etc/iotedge/config.yaml_backup
      cat /etc/iotedge/config.yaml_backup
