### ISSUE TITLE
Local debugging

### ISSUE THREAD

**Issue by payalsharma84** [social-experiments/EduOnEdge#9]

**Comment by annadhpi** [comment]
instruction has uploaded 
here[https://microsoft.sharepoint.com/teams/JPEngagement/_layouts/OneNote.aspx?id=%2Fteams%2FJPEngagement%2FSiteAssets%2FJP%20Engagement%20Notebook&wd=target%28Instruction.one%7CA050EE41-EB49-47CC-B9F5-66AD246EF736%2FBuild%20and%20run%20in%20Simulator%7C62EC9B75-AB83-4AC7-BC8D-688F63410177%2F%29
onenote:https://microsoft.sharepoint.com/teams/JPEngagement/SiteAssets/JP%20Engagement%20Notebook/Instruction.one#Build%20and%20run%20in%20Simulator&section-id={A050EE41-EB49-47CC-B9F5-66AD246EF736}&page-id={62EC9B75-AB83-4AC7-BC8D-688F63410177}&end](url)

**Comment by annadhpi** [comment]
[](https://github.com/social-experiments/EduOnEdge/issues/9)
